import json, sys, re
sys.path.insert(0,'/workspace/do-craft-build/extra')
import restore_data1 as a, restore_data2 as b
S=a.STAGES1+b.STAGES2
assert len(S)==30
def norm(s):
    return dict(t=list(s['t']),b=s['b'],d=s['d'],x=s['x'],w=s['w'],q=[list(q) for q in s['q']],
      s=[s['s'][0],[list(c) for c in s['s'][1]]],r=s['r'],c=[s['c'][0],list(s['c'][1]),s['c'][2]])
data=json.dumps([norm(s) for s in S],ensure_ascii=False)
d='/workspace/do-craft-build/extra/'
def rd(f): return open(d+f,encoding='utf8').read()
datafiles=[rd('data/'+f+'.js') for f in ('brain1','brain2','brain3','proc1','proc2','dragon1','dragon2')]
datafiles.append("const BR_DATA=[...BR1,...BR2,...BR3];const PR_DATA=[...PR1,...PR2];const DR_DATA=[...DR1,...DR2];\n")
parts=[rd('exercises.common.js'), "const RS = "+data+";\n", rd('exercises.restore.js'), rd('exercises.iq.js')]+datafiles+[rd('exercises.tracks.js'), rd('exercises.tail.js')]
out="/* generated by extra/assemble.py - exercise data for /restore and /iq */\n"+"\n".join(parts)
open(d+'exercises.mjs','w',encoding='utf8').write(out)
print(len(out))
