import json, sys, re
sys.path.insert(0,'/workspace/do-craft-build/extra')
import restore_data1 as a, restore_data2 as b
S=a.STAGES1+b.STAGES2
assert len(S)==30
def norm(s):
    return dict(t=list(s['t']),b=s['b'],d=s['d'],x=s['x'],w=s['w'],q=[list(q) for q in s['q']],
      s=[s['s'][0],[list(c) for c in s['s'][1]]],r=s['r'],c=[s['c'][0],list(s['c'][1]),s['c'][2]])
data=json.dumps([norm(s) for s in S],ensure_ascii=False)
d='/workspace/do-craft-build/extra/'
parts=[open(d+'exercises.common.js',encoding='utf8').read(), "const RS = "+data+";\n", open(d+'exercises.restore.js',encoding='utf8').read(), open(d+'exercises.iq.js',encoding='utf8').read(), open(d+'exercises.tail.js',encoding='utf8').read()]
out="/* generated by extra/assemble.py - exercise data for /restore and /iq */\n"+"\n".join(parts)
open(d+'exercises.mjs','w',encoding='utf8').write(out)
print(len(out))
